#!/bin/sh
if [ -f /var/mobile/Library/Filza/scripts/rootless-patcher.script ]; then
	echo "Removing rootless-patcher.script from Filza's scripts directory."
	rm /var/mobile/Library/Filza/scripts/rootless-patcher.script
fi